version: "3.8"
services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=bootcamp
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql


  app:
    depends_on:
      - mysqldb
    build: .
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
      MYSQL_PORT: 3306
    stdin_open: true
    tty: true

volumes:
  db: